[meta]
id = "com.redhat.rhsm.hourly"
name = "Red Hat Subscription Management for public clouds"

[exec]
shell = "./insights.d/org.example.mock"
content_type = "application/vnd.redhat.advisor.mock+tar.xz"
